name: CI/CD to AWS Lightsail

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # Agar Prisma ishlatilayotgan bo‘lsa
      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build project
        run: npm run build

      - name: Deploy files to AWS Lightsail
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          port: 22
          source: |
            dist/*
            package.json
            prisma/schema.prisma
            prisma/migrations/**
            sequelize/config/config.js
            sequelize/migrations/**
            sequelize/seeders/**
            ecosystem.config.js
          target: '/home/ubuntu/nestjs-app'

      - name: Restart App on Lightsail via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            cd /home/ubuntu/nestjs-app
            npm install --omit=dev

            # Prisma migration (agar kerak bo‘lsa)
            if [ -f "prisma/schema.prisma" ]; then
              npx prisma generate
              npx prisma migrate deploy
            fi

            # Sequelize migration
            if [ -d "sequelize/migrations" ]; then
              npx sequelize-cli db:migrate
            fi

            # Sequelize seed (ixtiyoriy)
            # npx sequelize-cli db:seed:all

            pm2 restart ecosystem.config.js || pm2 start ecosystem.config.js
